import org.krohm.milleborne.engineimpl.InternalActionExecutionContext;
import org.krohm.milleborne.actions.internalactions.*;
import org.krohm.milleborne.actions.returnactions.*;
import org.krohm.milleborne.actions.useractions.*;
import org.krohm.milleborne.actions.*;
import org.krohm.milleborne.data.*;
import org.krohm.milleborne.util.*;
import org.slf4j.Logger;

####
#
# START STEP
#
####
rule "START_2_INIT"
      salience 0
      dialect "java"
  when
      context : InternalActionExecutionContext (currentStep : currentStep == Steps.STEP_START)
  then
       context.setCurrentStep(Steps.STEP_INIT);
       modify ( context ) {}
end

####
#
# INIT STEP
#
####¨

rule "INIT_2_STEP_USER_ACTION"
      salience 0
      dialect "java"
  when
      context : InternalActionExecutionContext (currentStep == Steps.STEP_INIT)
  then
       context.setCurrentStep(Steps.STEP_USER_ACTION);
       modify ( context ) {}
end

####
#
# USER_ACTION STEP
#
####

#
# Internal Step is used to avoid re-checking other rules of this step and recalculate Other
# Rules confitions
#
rule "STEP_USER_ACTION_2_INTERNAL"
      salience 0
      dialect "java"
  when
      context : InternalActionExecutionContext (currentStep == Steps.STEP_USER_ACTION)
  then
       context.setCurrentStep(Steps.InternalSteps.INTERNAL_STEP_USER_ACTION);
       modify ( context ) {}
end

rule "STEP_USER_ACTION_2_STEP_ERROR"
      salience 1
      dialect "java"
  when
      context : InternalActionExecutionContext (currentStep == Steps.InternalSteps.INTERNAL_STEP_USER_ACTION, todoList : todoList)
      eval (todoList.size() < 1)
  then
       Logger logger = DrlUtil.getLogger();
       context.setReturnAction(new InvalidAction());
       context.setCurrentStep(Steps.STEP_ERROR);
       modify ( context ) {}
end

rule "STEP_USER_ACTION_2_STEP_BEFORE_EXEC"
      salience 0
      dialect "java"
  when
      context : InternalActionExecutionContext (currentStep == Steps.InternalSteps.INTERNAL_STEP_USER_ACTION)
  then
       context.setCurrentStep(Steps.STEP_BEFORE_EXEC);
       modify ( context ) {}
end

####
#
# BEFORE_EXEC STEP
#
####

#
# TODO : add rule to verify if currentAction have been validated or not
# and jump to error / skip if required
#

rule "STEP_BEFORE_EXEC_2_ERROR"
      salience 1
      dialect "java"
  when
      context : InternalActionExecutionContext (currentStep == Steps.STEP_BEFORE_EXEC,
            todoList : todoList,
            currentAction : todoList.peek)
            eval ( ((IInternalAction)currentAction).getValidationStatus()  == IInternalAction.STATUS_REJECTED)
then
       Logger logger = DrlUtil.getLogger();
       logger.error("Action REJECTED: <" + currentAction +">");
       context.setCurrentStep(Steps.STEP_ERROR);
       modify ( context ) {}
end


rule "STEP_BEFORE_EXEC_2_STEP_EXEC"
      salience 0
      dialect "java"
  when
      context : InternalActionExecutionContext (currentStep == Steps.STEP_BEFORE_EXEC)
  then
       context.setCurrentStep(Steps.STEP_EXEC);
       modify ( context ) {}
end


####
#
# EXEC STEP
#
####

rule "STEP_EXEC_2_INTERNAL"
      salience 0
      dialect "java"
  when
      context : InternalActionExecutionContext (currentStep == Steps.STEP_EXEC)
  then
       IInternalAction currentAction = context.getTodoList().peek();
       Logger logger = DrlUtil.getLogger();
       logger.error("Executing Action : <" + currentAction +">");
       context.setCurrentStep(Steps.InternalSteps.INTERNAL_STEP_EXEC);
       modify ( context ) {}
end


rule "STEP_EXEC_2_STEP_AFTER_EXEC"
      salience 0
      dialect "java"
  when
      context : InternalActionExecutionContext (currentStep == Steps.InternalSteps.INTERNAL_STEP_EXEC)
  then
       context.setCurrentStep(Steps.STEP_AFTER_EXEC);
       modify ( context ) {}
end

####
#
# AFTER_EXEC STEP
#
####

rule "AFTER_EXEC_2_INTERNAL"
      salience 0
      dialect "java"
  when
      context : InternalActionExecutionContext (currentStep == Steps.STEP_AFTER_EXEC)
  then
       IInternalAction currentAction = context.getTodoList().poll();
       Logger logger = DrlUtil.getLogger();
       logger.error("Removing Action : <" + currentAction +">");
       context.setCurrentStep(Steps.InternalSteps.INTERNAL_STEP_AFTER_EXEC);
       modify ( context ) {}
end

rule "STEP_EXEC_2_STEP_BEFORE_EXEC_LOOP"
      salience 1
      dialect "java"
  when
      context : InternalActionExecutionContext (currentStep == Steps.InternalSteps.INTERNAL_STEP_AFTER_EXEC, todoList : todoList)
      eval (todoList.size() > 0)
  then
       context.setCurrentStep(Steps.STEP_BEFORE_EXEC);
       modify ( context ) {}
end

rule "STEP_AFTER_EXEC_2_STEP_END"
      salience 0
      dialect "java"
  when
      context : InternalActionExecutionContext (currentStep == Steps.InternalSteps.INTERNAL_STEP_AFTER_EXEC)
  then
       context.setCurrentStep(Steps.STEP_END);
       modify ( context ) {}
end

####
#
# END STEP
#
####

# No Rules for END STEP  : this is the end

####
#
# END STEP
#
####

# Replaces any non-error ReturnAction (including null) by default Error Action
rule "UNKNOWN_ERROR"
      salience 0
      dialect "java"
  when
      context : InternalActionExecutionContext (currentStep == Steps.STEP_ERROR, returnAction : returnAction)
      eval (! ( returnAction instanceof ErrorReturnAction))
  then
       context.setReturnAction(new UnknownErrorAction());
       modify ( context ) {}
end

